### ISSUE TITLE
Failed to build AMF from scratch

### ISSUE THREAD

**Issue by meng72** [omec-project/amf#53]
I was trying to build amf from the branch of `onf-release3.0.5` which I assume is the latest version. 

However, `docker build .` returns `go: github.com/omec-project/config5g@v1.0.1: reading github.com/omec-project/config5g/go.mod at revision v1.0.1: unknown revision v1.0.1`. It seems that the `config5g` repo is needed which I can't find anywhere. 

Could anyone help me with it? Thanks in advance!

**Comment by gab-arrobo** [comment]
> I was trying to build amf from the branch of `onf-release3.0.5` which I assume is the latest version.

I do not see the branch in the `amf` repo.

> However, `docker build .` returns `go: github.com/omec-project/config5g@v1.0.1: reading github.com/omec-project/config5g/go.mod at revision v1.0.1: unknown revision v1.0.1`. It seems that the `config5g` repo is needed which I can't find anywhere.

Here is located the package: https://github.com/omec-project/config5g/releases/tag/v1.0.1. However, the problem i think is related to the branch, which I do not see that it exists in the `amf` repo
 
> Could anyone help me with it? Thanks in advance!
